### ISSUE TITLE
4KID

### ISSUE THREAD

**Issue by djdll** [zzr-idam/4KDehazing#18]
In your work（Single UHD Image Dehazing via Interpretable Pyramid Network）, do you have the 4KID dataset link? Thank you for your work.

**Comment by zzr-idam** [comment]
链接：https://pan.baidu.com/s/1evOSCjjwZGU5qTZc7uMmJA?pwd=zm5l&nbsp;
提取码：zm5l&nbsp;


----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Jiang&nbsp;Du ***@***.***&gt;;
发送时间：2023年5月26日(星期五) 中午11:16
收件人："zzr-idam/4KDehazing" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[zzr-idam/4KDehazing] 4KID (Issue #18)
-----------------------------------

 

 
In your work（Single UHD Image Dehazing via Interpretable Pyramid Network）, do you have the 4KID dataset link? Thank you for your work.

**Comment by djdll** [comment]
Thank you for your reply. When I used test.py to test real foggy images, it performed very poorly. Is this correct even for real foggy images?
![pred_Lap11_Lap1](https://github.com/zzr-idam/4KDehazing/assets/57391029/b1e617f0-7b22-4629-a3b9-cf1effea58f6)

**Comment by djdll** [comment]
In your work（Single UHD Image Dehazing via Interpretable Pyramid Network）,In the paper, you have the comparison image of dehazing in real data. Could you please provide the image used in your paper? We hope to use the same image as you for comparison experiments, and we are looking forward to your reply.

**Comment by inakierregueab** [comment]
Are you expecting to upload the dataset to Google Drive or Dropbox soon? It will be very helpful, thanks.
